project_name: confligt
builds:
  - binary: confligt
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
release:
  github:
    owner: alisaifee
    name: confligt
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
brew:
  github:
    owner: alisaifee
    name: homebrew-tap
  commit_author:
    name: Ali-Akber Saifee
    email: ali@indydevs.org
  folder: Formula
  description: "Find conflicting branches"
dockers:
  -
    binary: change-aws-password
    image: jaxxstorm/change-aws-password
    latest: true
fpm:
  vendor: Ali-Akber Saifee
  maintainer: Ali-Akber Saifee <ali@indydevs.org>
  description: "Find conflicting branches"
  license: MIT
  formats:
    - deb
