sudo: false
language: go
go:
- 1.9
- tip
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure
script:
- go vet ./...
cache:
  directories:
  - "./vendor"
notifications:
  email: false
after_success:
- test "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_GO_VERSION" = "1.9" -a -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser
  | bash
env:
  matrix:
    secure: oRNXaunyAutD3+nqXyT6zskub7ufUE2v2rL4VP2LYsmkwPIkdDIXtjxbXHg23Cik6epf5EPjDGW4DEHQKemuRjrsIiy3i/HJkCbRXjGIx7vWdig7quOFQQaH4g+4uuC5BZjkvGQF4eevrP9GIYu4IXr2nH1vPD63rToD4CKqra1TAzSC4uRshS8H8qkkaaiHFHSAa3DXMGFK35CI/aYkWr4ogRwxYZQLbXliYLrsa45Bb/elTgdg7fYLaDbXMdoT1sM/bnUPeHwO2GGiVVyAp63ZUZQganfHccSMbuLOBJ6kcdjRkBI0fHlEUR/U8wlZ/BAyv9IbRzKvgMXlp9DjJXBCzeCLXb81TmOv5JYm/HVBs5/BK9iGCcJxA/4xg5FumhkVRfpPZoDdtNznDzJxiSAMKfxRpGDKixllR0cqK1e8we/fxatRzQdqSesLQ1+f6YwHuUDcwsYlk16Td2qKPVdOm4L0G/TPmJ0JIhHNPqa0fHUW1W1b4fm2/ET2muoYBgLof0cbGgTrSDeHEXeFwchDZNUYaB0GDvBc7SyvmOYKPuum88y7tH3MmeBNMG0zKJtaPG0t0s0d/9wg+KWmGFZ5PFIYYXvdUq8A5L65ctsNhdE6+m49W3VMlpfXAQiuvpDktfvF2+okFB69W7vCYUJoe1/S3SP1sptF+VuF0kU=
